evaluate_gender_bias_task:
  description: >
    You are given the full text of a news article to analyze for gender bias:

    "{input_article}"

    Your goal is to evaluate the article for signs of **gender bias**. Look for:
      - Reinforcement of gender stereotypes
      - Gender-specific descriptions of individuals or professions
      - Emphasis on emotional display or appearance for women
      - One-sided gender representation in sources or viewpoints

    Based on your evaluation, return a JSON object using the following structure:

    ```json
    {{
      "category": "gender_bias",
      "gender_bias_score": <number between 0 (no bias) and 100 (strong bias)>,
      "gender_bias_explanation": "<Brief explanation of why this score was given, citing key observations>"
    }}
    ```

  expected_output: >
    A JSON object with category, bias score (0–100), and explanation string

review_ethics_task:
  description: >
    Review the following news article for potential ethical violations or risks:

    "{input_article}"

    Refer to well-known journalism frameworks such as:
      - SPJ Code of Ethics
      - Reuters Trust Principles
      - BBC Editorial Guidelines

    Focus on four key principles:
      - Accuracy
      - Fairness
      - Independence
      - Transparency

    For each violation or risk you identify, specify:
      - The principle involved
      - A short quote or summary that illustrates the issue
      - A reference to the specific guideline or principle that is being violated or stretched

    Return the output in the following format:

    ```json
    {{
      "ethical_review": {{
        "violations": [
          {{
            "principle": "Fairness",
            "description": "The article relies exclusively on law enforcement sources without alternative viewpoints.",
            "reference": "SPJ Code of Ethics – Provide context and avoid stereotyping."
          }}
        ]
      }}
    }}
    ```

  expected_output: >
    JSON object listing any violations of journalism ethics.
